token:
  expiration_time: 86400000
  # secret: user_token_native_application
  secret: '{cipher}AQCBdR3ND2ijM6/2zms4RrsU+GX4qHNF4Li34OF30+YxFIWPWixA5jLD8Sp+rdVXEz59xcxnAlW3d3xtKkA+r41Hd6I8fJvWqFR5XrYkm6kg6a5MHmpAFDpE7AHBduFxFD2VuBhZUtDxZjsXAzsFbOGN1b1idBbQZwFUbtPA7Ks+LdLltHkfy6ySNTdVvNld2EuRfTb9cYIAIA3DPyh9RoDNB1JIyTlVx85FrwdsLBvNZ+SHIJP3pHd7bK8ppBRUPdDvaCSiuhcneubXD48UfPCETNLK3HABEDP2zEYvImlWJORyQ68lIZtEP9qTg01IB+tilEQb39KupR5oJM82cv0Edbu5fZVcXkdofOfVIEFH/F/ko9jPVYAgPfgG0v4C2XRMbwgc9OViTSNy66OwIRNO'

gateway:
  ip: 172.18.0.5