spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}134119f1b4342ab06d4d10430f34669aa8e8656a1e2854117114c56a146ce4bb'

token:
  expiration_time: 86400000
  secret: user_token_native_user-service

gateway:
  ip: 172.0.0.1